entry-pipeline:
  workers: 8
  source:
    otel_trace_source:
      ssl: false
      authentication:
        unauthenticated:
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  sink:
    - pipeline:
        name: "raw-trace-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-trace-pipeline:
  workers: 8
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 64
  processor:
    - otel_trace_raw:
        # flatten_attributes: false
        # output_format: "otel"
    - otel_trace_group:
        hosts: [ "http://opensearch-node1:9200" ]
        username: "admin"
        password: "MyPassword123!"
  sink:
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        insecure: true
        username: admin
        password: MyPassword123!
        # index_type: trace-analytics-raw
        index_type: custom
        index: otel-v1-apm-span-agent
        template_file: ml_agent_trace.json
        template_type: index-template
        # bulk_size: 4
        # number_of_shards: 5
        # number_of_replicas: 1
        # template_file: /path/to/index-template.json
        # template_file: common/src/main/resources/index-mappings/ml_agent_trace.json

service-map-pipeline:
  workers: 8
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
        window_duration: 360
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  sink:
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        insecure: true
        username: admin
        password: MyPassword123!
        index_type: trace-analytics-service-map